### ISSUE TITLE
Change `nearest_node` API

### ISSUE THREAD

**Issue by mmiller-max** [DeloitteOptimalReality/LightOSM.jl#45]
Unfortunately this will be a breaking change, so we should aim to release it along with any others (if there are any in the pipeline)

If only one nearest node is requested, the output should not be a vector. Currently this is the output:
```Julia
julia> nearest_node(g, 1)
([[2]], [[0.1]])
```

And I think the output should be
```Julia
julia> nearest_node(g, 1)
(2, 0.1)
```

Then if more points are requested
```Julia
julia> nearest_node(g, 1, 2)
([2, 3], [0.1,0.1])
```
And if more locations are given
```Julia
julia> nearest_node(g, [1, 4], 2)
([[2, 3],[5, 6]], [[0.1,0.1],[0.1,0.1]])
```

Unfortunately that makes it type unstable. Could have `nearest_node` and `nearest_nodes` potentially?

**Comment by Datseris** [comment]
Yes, having `nearest_node` and `nearest_nodes` is the best way forwards in terms of design.
